server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
        url: lb://customer-service
        predicates:
          - Path=/customer/**
        - id: product-service
        url: lb://product-service
        predicates:
          - Path=/product/**
        - id: invoices-service
        url: lb://invoices-service
        predicates:
          - Path=/invoices/**
          